package no.nav.amt.tiltak.common.auth

enum class AdGruppe {
    TILTAKSANSVARLIG_FLATE_GRUPPE,
    TILTAKSANSVARLIG_ENDRINGSMELDING_GRUPPE,
    TILTAKSANSVARLIG_EGNE_ANSATTE_GRUPPE,
    TILTAKSANSVARLIG_FORTROLIG_ADRESSE_GRUPPE,
    TILTAKSANSVARLIG_STRENGT_FORTROLIG_ADRESSE_GRUPPE,
}
