version: '3.7'
services:
  amt-tiltak-postgres:
    image: 'postgres:12-alpine'
    container_name: amt-tiltak-postgres
    ports:
      - '5454:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=amt-tiltak-db

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.5
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: 8082
      JSON_CONFIG: >
        {
            "interactiveLogin": true,
            "httpServer": "NettyWrapper",
            "tokenCallbacks": [
                {
                    "issuerId": "local-tokenx",
                    "tokenExpiry": 31536000,
                    "requestMappings": [
                        {
                            "requestParam": "scope",
                            "match": "*",
                            "claims": {
                                "pid": "123456789",
                                "aud": "somescope"
                            }
                        }
                    ]
                }
            ]
        }

  ###### KAFKA ######
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "trade:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka
