version: '3.7'
services:
  amt-tiltak-postgres:
    image: 'postgres:12-alpine'
    container_name: amt-tiltak-postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - '5454:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=amt-tiltak-db
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.5
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082
volumes:
  postgres-db-volume:
