apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: amt-tiltak-alerts
  namespace: amt
  labels:
    team: amt
spec:
  receivers:
    slack:
      channel: 'team_komet_dev_alerts'
      prependText: ' | '
  alerts:
    - alert: applikasjon nede
      expr: kube_deployment_status_replicas_available{deployment="amt-tiltak"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.namespace }}"
      action: "`kubectl describe pod {{ $labels.pod }} -n {{ $labels.namespace }}` for events, og `kubectl logs {{ $labels.pod }} -n {{ $labels.namespace }}` for logger"
    - alert: høy feilrate i logger for amt-tiltak
      expr: (sum(rate(logd_messages_total{log_app="amt-tiltak",log_level=~"Fatal|Error"}[3m]))) > 0
      for: 3m
      action: "Sjekk loggene til app amt-tiltak i namespace amt for å se hvorfor det er så mye feil"
    - alert: antall feilede kafkameldinger i amt-tiltak > 0
      expr: amt_tiltak_antall_feilede_kafkameldinger{app="amt-tiltak"} > 0
      action: "Sjekk `kafka_consumer_record`-tabellen: `select * from kafka_consumer_record;`"
      for: 1m