apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: amt-tiltak-alerts
  namespace: amt
  labels:
    team: amt
spec:
  groups:
    - name: amt-tiltak-alerts
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="amt-tiltak"} == 0
          for: 2m
          annotations:
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
            action: "`kubectl describe pod -l app={{ $labels.deployment}}` -> `kubectl logs -l app={{ $labels.deployment}}`"
          labels:
            namespace: amt
            severity: critical
        - alert: høy feilrate i logger
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="amt-tiltak",level="Error"}[3m])) / sum by (app, namespace) (rate(log_messages_total{app="amt-tiltak"}[3m]))) > 10
          for: 3m
          annotations:
            action: "Sjekk loggene til app amt-tiltak i namespace amt, for å se hvorfor det er så mye feil"
          labels:
            namespace: amt
            severity: warning
