kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/amt-tiltak/amt-tiltak:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-tiltak.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: amt-tiltak-db
            envVarPrefix: DB
