kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-tiltak/amt-tiltak:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-tiltak.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
        - application: amt-tiltaksansvarlig-flate
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: prod-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: prod-gcp
        - application: amt-altinn-acl
          namespace: amt
          cluster: prod-gcp
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: ALTINN_KOORDINATOR_RETTIGHET_ID
      value: "9999999"
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: AMT_ALTINN_ACL_SCOPE
      value: api://prod-gcp.amt.amt-altinn-acl/.default
    - name: AMT_ALTINN_ACL_URL
      value: http://amt-altinn-acl.amt.svc.cluster.local
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://prod-gcp.amt.amt-enhetsregister/.default
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: NOM_SCOPE
      value: api://prod-gcp.nom.nom-api/.default
    - name: NOM_URL
      value: https://nom-api.intern.nav.no
    - name: NOM_MOCK
      value: "false"
    - name: VEILARBARENA_SCOPE
      value: api://prod-fss.pto.veilarbarena/.default
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://prod-fss.pto.veilarboppfolging/.default
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://prod-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.intern.nav.no
    - name: POAO_GCP_PROXY_SCOPE
      value: api://prod-fss.pto.poao-gcp-proxy/.default
    - name: POAO_GCP_PROXY_URL
      value: https://poao-gcp-proxy.prod-fss-pub.nais.io
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    # Kafka topics
    - name: SISTE_TILORDNET_VEILEDER_TOPIC
      value: pto.siste-tilordnet-veileder-v1
    - name: AMT_TILTAK_TOPIC
      value: amt.amt-tiltak-v1
    - name: ENDRING_PAA_OPPF_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: NAV_ENHET_TOPIC
      value: amt.nav-enhet-v1
  gcp:
    sqlInstances:
      - name: amt-tiltak-v1
        type: POSTGRES_14
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        databases:
          - name: amt-tiltak
            envVarPrefix: DB
