kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  webproxy: false
  ingresses:
    - https://amt-tiltak.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: {{ad_gruppe_egne_ansatte}}
          - id: {{ad_gruppe_tiltak_ansvarlig}}
          - id: {{ad_gruppe_endringsmelding}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
        - application: amt-tiltaksansvarlig-flate
        - application: amt-tiltaksarrangor-bff
        - application: amt-person-service
        - application: tiltakspenger-tiltak
          namespace: tpts
    outbound:
      rules:
        - application: amt-person-service
          namespace: amt
          cluster: prod-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: prod-gcp
        - application: amt-arrangor
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: veilarbarena.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: digdir-krr-proxy.intern.nav.no
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: AD_GRUPPE_ID_TILGANG_TIL_EGNE_ANSATTE
      value: {{ad_gruppe_egne_ansatte}}
    - name: AD_GRUPPE_ID_TILTAK_ANSVARLIG
      value: {{ad_gruppe_tiltak_ansvarlig}}
    - name: AD_GRUPPE_ID_ENDRINGSMELDING
      value: {{ad_gruppe_endringsmelding}}
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: AMT_ARRANGOR_SCOPE
      value: api://prod-gcp.amt.amt-arrangor/.default
    - name: AMT_ARRANGOR_URL
      value: http://amt-arrangor
    - name: AMT_PERSON_URL
      value: http://amt-person-service.amt.svc.cluster.local
    - name: AMT_PERSON_SCOPE
      value: api://prod-gcp.amt.amt-person-service/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.prod-fss-pub.nais.io
    - name: VEILARBARENA_SCOPE
      value: api://prod-fss.pto.veilarbarena/.default
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://prod-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://prod-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.intern.nav.no
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: MULIGHETSROMMET_API_SCOPE
      value: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: MULIGHETSROMMET_API_URL
      value: http://mulighetsrommet-api.team-mulighetsrommet.svc.cluster.local
    - name: UNLEASH_URL
      value: https://unleash.nais.io/api/
    # Kafka topics
    - name: SISTE_TILTAKSGJENNOMFORINGER_TOPIC
      value: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1
    - name: AMT_TILTAK_TOPIC
      value: amt.amt-tiltak-v1
    - name: DELTAKER_TOPIC
      value: amt.deltaker-v1
    - name: DELTAKER_TOPIC_V2
      value: amt.deltaker-v2
    - name: DELTAKERLISTE_TOPIC
      value: amt.deltakerliste-v1
    - name: ARRANGOR_TOPIC
      value: amt.arrangor-v1
    - name: ARRANGOR_ANSATT_TOPIC
      value: amt.arrangor-ansatt-v1
    - name: ENDRINGSMELDIG_TOPIC
      value: amt.endringsmelding-v1

  gcp:
    sqlInstances:
      - name: amt-tiltak-v1
        type: POSTGRES_14
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        databases:
          - name: amt-tiltak
            envVarPrefix: DB
