kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-tiltak/amt-tiltak:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-tiltak.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: {{ad_gruppe_egne_ansatte}}
          - id: {{ad_gruppe_tiltak_ansvarlig}}
          - id: {{ad_gruppe_endringsmelding}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
        - application: amt-tiltaksansvarlig-flate
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: dev-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: dev-gcp
        - application: amt-altinn-acl
          namespace: amt
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  env:
    - name: AD_GRUPPE_ID_TILGANG_TIL_EGNE_ANSATTE
      value: {{ad_gruppe_egne_ansatte}}
    - name: AD_GRUPPE_ID_TILTAK_ANSVARLIG
      value: {{ad_gruppe_tiltak_ansvarlig}}
    - name: AD_GRUPPE_ID_ENDRINGSMELDING
      value: {{ad_gruppe_endringsmelding}}
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: AMT_ALTINN_ACL_SCOPE
      value: api://dev-gcp.amt.amt-altinn-acl/.default
    - name: AMT_ALTINN_ACL_URL
      value: http://amt-altinn-acl.amt.svc.cluster.local
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://dev-gcp.amt.amt-enhetsregister/.default
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
    - name: NOM_URL
      value: https://nom-api.dev.intern.nav.no
    - name: NOM_MOCK
      value: "true"
    - name: NORG_URL
      value: https://norg2.dev-fss-pub.nais.io
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev-fss-pub.nais.io
    - name: VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-fss.pto.veilarboppfolging/.default
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.dev.intern.nav.no
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: MULIGHETSROMMET_API_SCOPE
      value: api://dev-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: MULIGHETSROMMET_API_URL
      value: http://mulighetsrommet-api.team-mulighetsrommet.svc.cluster.local
    # Kafka topics
    - name: SISTE_TILORDNET_VEILEDER_TOPIC
      value: pto.siste-tilordnet-veileder-v1
    - name: SISTE_TILTAKSGJENNOMFORINGER_TOPIC
      value: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1
    - name: AMT_TILTAK_TOPIC
      value: amt.amt-tiltak-v1
    - name: ENDRING_PAA_OPPF_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: SKJERMEDE_PERSONER_STATUS_TOPIC
      value: nom.skjermede-personer-status-v1
    - name: LEESAH_TOPIC
      value: pdl.leesah-v1
    - name: DELTAKER_TOPIC
      value: amt.deltaker-v1
    - name: AKTOR_V2_TOPIC
      value: pdl.aktor-v2
    - name: VIRKSOMHET_TOPIC
      value: amt.virksomheter-v1

  gcp:
    sqlInstances:
      - name: amt-tiltak-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: amt-tiltak
            envVarPrefix: DB
