kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-tiltak/amt-tiltak:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-tiltak.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate-auth-proxy
  env:
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://dev-gcp.amt.amt-enhetsregister/.default
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: amt-tiltak-db
            envVarPrefix: DB