kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak-temp
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  webproxy: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 50
  liveness:
    path: /internal/health/liveness
    initialDelay: 50
  replicas:
    disableAutoScaling: true
    min: 0
    max: 0
  resources:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: {{ad_gruppe_egne_ansatte}}
          - id: {{ad_gruppe_tiltak_ansvarlig}}
          - id: {{ad_gruppe_endringsmelding}}
          - id: {{ad_gruppe_fortrolig_adresse}}
          - id: {{ad_gruppe_strengt_fortrolig_adresse}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksansvarlig-flate
        - application: amt-tiltaksarrangor-bff
        - application: amt-arena-acl
        - application: amt-deltaker
        - application: tiltakspenger-tiltak
          namespace: tpts
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
        - application: veilarboppfolging
          namespace: pto
          cluster: prod-fss
        - application: veilarboppfolging
          namespace: poao
          cluster: prod-gcp
    outbound:
      rules:
        - application: amt-person-service
          namespace: amt
          cluster: prod-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: prod-gcp
        - application: amt-arrangor
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
      external:
        - host: amt-unleash-api.nav.cloud.nais.io
  kafka:
    pool: nav-prod
  envFrom:
    - secret: amt-tiltak-unleash-api-token
  env:
    - name: AD_GRUPPE_ID_TILGANG_TIL_EGNE_ANSATTE
      value: {{ad_gruppe_egne_ansatte}}
    - name: AD_GRUPPE_ID_TILTAK_ANSVARLIG
      value: {{ad_gruppe_tiltak_ansvarlig}}
    - name: AD_GRUPPE_ID_ENDRINGSMELDING
      value: {{ad_gruppe_endringsmelding}}
    - name: AD_GRUPPE_ID_FORTROLIG_ADRESSE
      value: {{ad_gruppe_fortrolig_adresse}}
    - name: AD_GRUPPE_ID_STRENGT_FORTROLIG_ADRESSE
      value: {{ad_gruppe_strengt_fortrolig_adresse}}
    - name: AMT_ARRANGOR_SCOPE
      value: api://prod-gcp.amt.amt-arrangor/.default
    - name: AMT_ARRANGOR_URL
      value: http://amt-arrangor
    - name: AMT_PERSON_URL
      value: http://amt-person-service.amt.svc.cluster.local
    - name: AMT_PERSON_SCOPE
      value: api://prod-gcp.amt.amt-person-service/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: MULIGHETSROMMET_API_SCOPE
      value: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: MULIGHETSROMMET_API_URL
      value: http://mulighetsrommet-api.team-mulighetsrommet.svc.cluster.local
    # Kafka topics
    - name: SISTE_TILTAKSGJENNOMFORINGER_TOPIC
      value: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1
    - name: AMT_TILTAK_TOPIC
      value: amt.amt-tiltak-v1
    - name: DELTAKER_TOPIC
      value: amt.deltaker-v1
    - name: DELTAKER_TOPIC_V2
      value: amt.deltaker-v2
    - name: ARRANGOR_TOPIC
      value: amt.arrangor-v1
    - name: ARRANGOR_ANSATT_TOPIC
      value: amt.arrangor-ansatt-v1
    - name: ENDRINGSMELDIG_TOPIC
      value: amt.endringsmelding-v1
    - name: NAV_BRUKER_PERSONALIA_TOPIC
      value: amt.nav-bruker-personalia-v1
    - name: NAV_ANSATT_PERSONALIA_TOPIC
      value: amt.nav-ansatt-personalia-v1

  gcp:
    sqlInstances:
      - name: amt-tiltak
        type: POSTGRES_17
        diskAutoresize: false
        highAvailability: false
        pointInTimeRecovery: false
        tier: db-custom-1-3840
        databases:
          - name: amt-tiltak
            envVarPrefix: DB
            users:
              - name: datastream
        flags:
          - name: cloudsql.logical_decoding
            value: "on"

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
