kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltak
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-tiltak/amt-tiltak:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-tiltak.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "f12fa5d6-ef0c-41db-80c9-5c9696bb5c14" # 0000-GA-Tiltaksansvarlig, NAV Preprod
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
        - application: amt-tiltaksansvarlig-flate
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: dev-gcp
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  env:
    - name: AXSYS_SCOPE
      value: api://dev-fss.org.axsys/.default
    - name: AXSYS_URL
      value: https://axsys.dev.intern.nav.no
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://dev-gcp.amt.amt-enhetsregister/.default
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
    - name: NOM_URL
      value: https://nom-api.dev.intern.nav.no
    - name: NOM_MOCK
      value: "true"
    - name: VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-fss.pto.veilarboppfolging/.default
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.dev.intern.nav.no
    - name: POAO_GCP_PROXY_SCOPE
      value: api://dev-fss.pto.poao-gcp-proxy/.default
    - name: POAO_GCP_PROXY_URL
      value: https://poao-gcp-proxy.dev-fss-pub.nais.io
    # Kafka topics
    - name: SISTE_TILORDNET_VEILEDER_TOPIC
      value: pto.siste-tilordnet-veileder-v1
    - name: AMT_TILTAK_TOPIC
      value: amt.amt-tiltak-v1
    - name: ENDRING_PAA_OPPF_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
  gcp:
    sqlInstances:
      - name: amt-tiltak-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: amt-tiltak
            envVarPrefix: DB
