package no.nav.amt.tiltak.tools.token_provider.utils

object AzureAdEnvironmentVariables {

	const val AZURE_OPENID_CONFIG_TOKEN_ENDPOINT = "AZURE_OPENID_CONFIG_TOKEN_ENDPOINT"

	const val AZURE_APP_CLIENT_ID = "AZURE_APP_CLIENT_ID"

	const val AZURE_APP_TENANT_ID = "AZURE_APP_TENANT_ID"

	const val AZURE_APP_CLIENT_SECRET = "AZURE_APP_CLIENT_SECRET"

	const val AZURE_APP_PRE_AUTHORIZED_APPS = "AZURE_APP_PRE_AUTHORIZED_APPS"

	const val AZURE_APP_WELL_KNOWN_URL = "AZURE_APP_WELL_KNOWN_URL"

	const val AZURE_APP_JWKS = "AZURE_APP_JWKS"

	const val AZURE_APP_JWK = "AZURE_APP_JWK"

	const val AZURE_OPENID_CONFIG_JWKS_URI = "AZURE_OPENID_CONFIG_JWKS_URI"

	const val AZURE_OPENID_CONFIG_ISSUER = "AZURE_OPENID_CONFIG_ISSUER"

	const val AZURE_APP_CERTIFICATE_KEY_ID = "AZURE_APP_CERTIFICATE_KEY_ID"

	const val AZURE_APP_PASSWORD_KEY_ID = "AZURE_APP_PASSWORD_KEY_ID"


	const val AZURE_APP_NEXT_JWK = "AZURE_APP_NEXT_JWK"

	const val AZURE_APP_NEXT_CLIENT_SECRET = "AZURE_APP_NEXT_CLIENT_SECRET"

	const val AZURE_APP_NEXT_CERTIFICATE_KEY_ID = "AZURE_APP_NEXT_CERTIFICATE_KEY_ID"

	const val AZURE_APP_NEXT_PASSWORD_KEY_ID = "AZURE_APP_NEXT_PASSWORD_KEY_ID"

}
