name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts-prod.yaml'
      - '.github/workflows/deploy-alerts-prod.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts-prod.yaml
