name: Run tests with Gradle
on:
  workflow_call:
  push:
    branches-ignore:
      - main

env:
  TZ: Europe/Oslo

jobs:
  test:
    permissions:
      contents: "write"
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests with Gradle
        run: ./gradlew clean check --build-cache --info